apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pingpong-app
  namespace: argocd
  labels:
    app: pingpong
spec:
  project: default
  
  source:
    repoURL: https://github.com/yismaili/pingpong-gitops.git
    targetRevision: HEAD
    path: k8s-manifests
  
  destination:
    server: https://kubernetes.default.svc
    namespace: pingpong
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true