apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pingpong
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc-eks.yaml
  - postgres-deploment.yaml
  - postgres-service.yaml
  - backend-deploment.yaml
  - backend-service.yaml
  - frontend-deploment.yaml
  - frontend-service.yaml
  - ingress.yaml
commonLabels:
  app: pingpong
  managed-by: argocd